# Generated by Django 5.2 on 2025-04-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=250)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('info', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='EVChargingLocation',
        ),
    ]
