# Generated by Django 5.2 on 2025-04-08 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0003_evcharginglocation_delete_wifispot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evcharginglocation',
            old_name='station_name',
            new_name='SSID',
        ),
    ]
