# Generated by Django 5.2 on 2025-04-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('war_drive_app', '0004_rename_station_name_evcharginglocation_ssid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EVChargingLocation',
            new_name='WiFi',
        ),
    ]
